name: AgriCam Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  # Job 1 — Scan de sécurité Checkov
  scan-securite:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Checkov
        run: pip install checkov

      - name: Scanner le code Terraform
        run: |
          checkov -d . --framework terraform \
            --check CKV_AWS_19 \
            --check CKV_AWS_24 \
            --check CKV2_AWS_11 \
            --check CKV_AWS_86 \
            --check CKV_AWS_36

  # Job 2 — Terraform Plan (prévisualisation)
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: scan-securite
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

      - name: Terraform Plan
        run: terraform plan -var="account_id=${{ secrets.AWS_ACCOUNT_ID }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

  # Job 3 — Terraform Apply (déploiement uniquement sur main)
  terraform-deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

      - name: Terraform Apply
        run: terraform apply -var="account_id=${{ secrets.AWS_ACCOUNT_ID }}" -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
